### ISSUE TITLE
ADC cannot be used with M5Unified and Arduino3.0.4

### ISSUE THREAD

**Issue by tanakamasayuki** [m5stack/M5Unified#121]
```c
#include <M5Unified.h>

void setup() {
  auto cfg = M5.config();
  M5.begin(cfg);
  analogReadResolution(12);
}

void loop() {
  M5.delay(1000);
  M5.Log.println("loop");
}
```

Hang up at analogReadResolution().

```
E (119) ADC: CONFLICT! driver_ng is not allowed to be used with the legacy driver
```

This error occurred.
Therefore, I will use Arduino2.x.

**Comment by lovyan03** [comment]
@tanakamasayuki 
Thank you for reporting this.
We will be fixing the code that relies on legacy drivers such as ADC and I2S.

**Comment by ainyan03** [comment]
棚卸のためのメモです（メンテナではありません）。

この件は 0360b63「tweak ADC driver for ESP-IDF 5.x.x ( ArduinoESP32 v3.x.x )」（コミットメッセージに #89 #90 #121 が明記されています）で対応済みで、**v0.1.17 (2024-09-23)** に含まれています。

現在はコンパイル時にドライバを選択し、ESP-IDF v5 系では `adc_oneshot_*` を使う実装になっています。

https://github.com/m5stack/M5Unified/blob/2fe93c0/src/utility/Power_Class.hpp#L24-L30
https://github.com/m5stack/M5Unified/blob/2fe93c0/src/utility/Power_Class.cpp#L1429-L1462

クローズ候補と思われます。

**Comment by tanakamasayuki** [comment]
```
  m5stack_cores3:
    fqbn: esp32:esp32:m5stack_cores3
    platforms:
      - platform: esp32:esp32 (3.3.11)
        platform_index_url: https://espressif.github.io/arduino-esp32/package_esp32_index.json
    libraries:
      - M5Unified (0.2.19)
      - M5GFX (0.2.26)
```

この環境で問題なく動きました
